my-awesome-container:
  image: my-awesome-image

backup:
  image: ckulka/awscli
  volumes_from:
    - my-awesome-container
  environment:
    - AWS_ACCESS_KEY_ID=my-access-key-id
    - AWS_SECRET_ACCESS_KEY=my-access-key-secret
    - AWS_DEFAULT_REGION=eu-central-1
    - BACKUP_LOCAL=/var/app/config
    - BACKUP_S3=s3://my-backup-bucket/app
#    - BACKUP_CHOWN=my-user (optional)
  command: "sh /opt/aws-s3-sync-restore.sh"
